@baseUrl = {{apiUrl}}/api/users

### Create User
POST {{baseUrl}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "firstName": "Ángel",
  "lastName": "Cruz",
  "email": "test@angelcruzl.dev",
  "username": "angelcruzl",
  "password": "Secret123"
}

### Get User list
GET {{baseUrl}}

### Get User by ID
GET {{baseUrl}}/2
Authorization: Bearer {{auth_token}}

### Update User
PUT {{baseUrl}}/2
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "admin": true
}

### Update User password
PATCH {{baseUrl}}/2/password
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "newPassword": "NewSecret123",
  "currentPassword": "Secret123"
}

### Delete User
DELETE {{baseUrl}}/1
Authorization: Bearer {{auth_token}}
